import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-captive-insurance-collateral-reconciliation",
  "engine": "recovery",
  "title": "Captive Insurance Collateral Reconciliation",
  "shortTitle": "Captive Insurance Collateral Reconciliation",
  "tagline": "Reduce trapped capital by independently calculating collateral requirements and supporting timely release requests.",
  "industry": "Captive Insurance Finance",
  "buyer": "Captives, risk managers, and fronting carriers",
  "uiPort": 4665,
  "apiPort": 5665,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Captive Insurance Collateral Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases in one accountable workflow. Reduce trapped capital by independently calculating collateral requirements and supporting timely release requests.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Captive Insurance Collateral Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("fronting-agreement-library","CIC01","Fronting agreement library","Execute fronting agreement library using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed fronting agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Fronting agreement library Reference","text","CIC01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("program-year-registry","CIC02","Program year registry","Execute program year registry using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed program year registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Program year registry Reference","text","CIC02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("loss-run-ingestion","CIC03","Loss run ingestion","Execute loss run ingestion using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed loss run ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Loss run ingestion Reference","text","CIC03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("case-reserve-validation","CIC04","Case reserve validation","Execute case reserve validation using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed case reserve validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Case reserve validation Reference","text","CIC04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("ibnr-methodology","CIC05","IBNR methodology","Execute ibnr methodology using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed ibnr methodology decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","IBNR methodology Reference","text","CIC05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("paid-loss-credit","CIC06","Paid loss credit","Execute paid loss credit using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed paid loss credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Paid loss credit Reference","text","CIC06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("premium-offset-control","CIC07","Premium offset control","Execute premium offset control using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed premium offset control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Premium offset control Reference","text","CIC07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("collateral-formula-calculation","CIC08","Collateral formula calculation","Execute collateral formula calculation using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed collateral formula calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Collateral formula calculation Reference","text","CIC08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("instrument-inventory","CIC09","Instrument inventory","Execute instrument inventory using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed instrument inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Instrument inventory Reference","text","CIC09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("letter-of-credit-fee-audit","CIC10","Letter-of-credit fee audit","Execute letter-of-credit fee audit using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed letter-of-credit fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Letter-of-credit fee audit Reference","text","CIC10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("trust-asset-reconciliation","CIC11","Trust asset reconciliation","Execute trust asset reconciliation using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed trust asset reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Trust asset reconciliation Reference","text","CIC11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("release-opportunity-detection","CIC12","Release opportunity detection","Execute release opportunity detection using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed release opportunity detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Release opportunity detection Reference","text","CIC12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("fronting-carrier-request","CIC13","Fronting carrier request","Execute fronting carrier request using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed fronting carrier request decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Fronting carrier request Reference","text","CIC13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("accounting-close-reconciliation","CIC14","Accounting close reconciliation","Execute accounting close reconciliation using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed accounting close reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Accounting close reconciliation Reference","text","CIC14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]}),
feature("program-capital-analytics","CIC15","Program capital analytics","Execute program capital analytics using fronting agreements, loss runs, reserves, IBNR, paid losses, premiums, security requirements, letters of credit, trusts, and releases.","Produce a governed program capital analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Collateral Instrument","text","Program / Collateral Instrument · Standard Case"],["caseReference","Program capital analytics Reference","text","CIC15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",810000],["supportedAmount","Evidence-Supported Amount","currency",680400],["domainDriver","Security Type","select","Letter of credit",["Letter of credit","Trust","Parental guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Fronting agreement library case","Program year registry case","Loss run ingestion case","Case reserve validation case","IBNR methodology case"]})
]);
